# numpy methods 

In [3]:
import numpy as np

# zeros

In [4]:
x=np.zeros((3,3))

In [5]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# ones

In [6]:
a=np.ones((2,3))

In [7]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

# empty

In [15]:
x=np.empty((2,2))

In [16]:
x

array([[0., 0.],
       [0., 0.]])

# numpy array

In [10]:
a=[6,7,8,9]

In [11]:
x=np.array(a)

In [12]:
x

array([6, 7, 8, 9])

# arange

In [50]:
r=np.arange(10)

In [51]:
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
r=np.arange(0,20,5)

In [57]:
r

array([ 0,  5, 10, 15])

# shape..........without brackets becuase its an attribute not method

In [52]:
x=np.ones((5,3))

In [55]:
x.shape

(5, 3)

In [56]:
x=np.zeros((10,10))

In [57]:
x.shape

(10, 10)

In [58]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# dtype......without brackets becuase its an attribute not method

In [59]:
x.dtype      # dtype is used for identify numpy ndarray data type 

dtype('float64')

In [60]:
type(x)    # type() used for identify simple python variable data type

numpy.ndarray

In [61]:
a=["a","b","c","d"]

In [65]:
abc=np.array(a)

In [66]:
abc.dtype

dtype('<U1')

# ndim.........for dimensions checking and its an attribute

In [67]:
abc.ndim

1

In [68]:
x.ndim

2

# for eg

In [69]:
b=np.zeros((2,2,2,2))

In [70]:
b.ndim

4

In [17]:
import numpy as np

In [29]:
c=np.arange(10)

# reshape()

In [36]:
c.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# itemsize

In [31]:
c.itemsize

4

# type()

In [32]:
type(c)

numpy.ndarray

# size

In [37]:
arr=np.ones((3,2))

In [38]:
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
arr.size

6

# we can define data type at the time of array creation

In [53]:
a=np.ones((5,6),dtype=np.int16)

In [54]:
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

# linspace()

In [64]:
a=np.linspace(0,2,11)    # alternate of arange() when we deal with floating point data we use linspace instead of arange

In [65]:
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [74]:
arr=np.random.randn(5,4)

In [75]:
arr

array([[-0.45862811,  0.54890098,  0.11766727, -0.40330402],
       [ 1.34889873, -0.84649788,  0.75683433, -0.22631927],
       [-2.17373855, -1.1567826 ,  0.56954116,  0.73051625],
       [ 0.95784035, -1.70518722,  0.59578258, -0.75886818],
       [ 0.43340636, -0.19291891, -0.5489838 , -0.37402169]])

In [78]:
arr.reshape(2,5,2)

array([[[-0.45862811,  0.54890098],
        [ 0.11766727, -0.40330402],
        [ 1.34889873, -0.84649788],
        [ 0.75683433, -0.22631927],
        [-2.17373855, -1.1567826 ]],

       [[ 0.56954116,  0.73051625],
        [ 0.95784035, -1.70518722],
        [ 0.59578258, -0.75886818],
        [ 0.43340636, -0.19291891],
        [-0.5489838 , -0.37402169]]])

In [79]:
arr

array([[-0.45862811,  0.54890098,  0.11766727, -0.40330402],
       [ 1.34889873, -0.84649788,  0.75683433, -0.22631927],
       [-2.17373855, -1.1567826 ,  0.56954116,  0.73051625],
       [ 0.95784035, -1.70518722,  0.59578258, -0.75886818],
       [ 0.43340636, -0.19291891, -0.5489838 , -0.37402169]])

# ravel() and flatten()

In [80]:
arr.ravel()

array([-0.45862811,  0.54890098,  0.11766727, -0.40330402,  1.34889873,
       -0.84649788,  0.75683433, -0.22631927, -2.17373855, -1.1567826 ,
        0.56954116,  0.73051625,  0.95784035, -1.70518722,  0.59578258,
       -0.75886818,  0.43340636, -0.19291891, -0.5489838 , -0.37402169])

In [81]:
arr.flatten()

array([-0.45862811,  0.54890098,  0.11766727, -0.40330402,  1.34889873,
       -0.84649788,  0.75683433, -0.22631927, -2.17373855, -1.1567826 ,
        0.56954116,  0.73051625,  0.95784035, -1.70518722,  0.59578258,
       -0.75886818,  0.43340636, -0.19291891, -0.5489838 , -0.37402169])